# Generated by Django 3.1 on 2020-08-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200813_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='sharedWith',
            new_name='shared_with',
        ),
    ]
