version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A cjapp worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis